
hooks:
    after:bump: "sh auto-changelog.sh && npx cordova-set-version",
    after:release: "echo Successfully released ${name} v${version} to ${repo.repository}."

git:
    requireCleanWorkingDir: false
    requireCommits: true
    addUntrackedFiles: true
    commit: true
    commitMessage: "Release ${version}"
    tag: true
    tagAnnotation: "Release ${version}"
    push: true

npm:
    publish: true

github:
    release: false

gitlab:
    release: false
